### ISSUE TITLE
cpp-capture not working

### ISSUE THREAD

**Issue by mbelluzzo** [intel-aero/intel-aero-manifest#2]
After build an image based on master branch (that was pointing to tag v01.00.04) and install on Intel aero, the cpp-capture sample that ships with the image stop working.

The same doesn't happens with the official release, so it may be some difference/missing here.

I will post the error message soon (need to burn the image again after testing with the official release). Its UVC related, but as far I could verify, librealsense addtional patches to the kernel build were applied during bitbake.

**Comment by vilvo** [comment]
Thanks @mbelluzzo - I'm in the process of updating the kernel from 4.4.3 to 4.4.41 and noticed that some patches would require work. I'll check cpp-capture support also when we get closer to the next release.

**Comment by mindThomas** [comment]
Any news on this problem?

**Comment by vilvo** [comment]
Unfortunately not yet - I´ll sync our meta-ros fork from upstream to check https://github.com/intel-aero/meta-intel-aero/issues/25 before studying this further.

**Comment by lucasdemarchi** [comment]
@mbelluzzo can we close this?

**Comment by mbelluzzo** [comment]
sure
