### ISSUE TITLE
zlib-native-1.2.8-r0 fetch error

### ISSUE THREAD

**Issue by mindThomas** [intel-aero/intel-aero-manifest#4]
When bitbaking using this manifest I get the following error/warning:
Failed to fetch URL http://www.zlib.net/zlib-1.2.8.tar.xz, attempting MIRRORS if available

**Comment by mindThomas** [comment]
Further errors with:
- libpcre-native-8.38-r0
- libpng-native-1.6.21-r0

**Comment by vilvo** [comment]
Thanks, we discussed this also on the community forum where I provided this answer - https://communities.intel.com/message/459130#459130 

To follow this and other build issues I just change Jenkins to build the release-manifest in AWS every second hour - http://ec2-52-59-242-235.eu-central-1.compute.amazonaws.com:8080/job/aero-build-release/ - it´s not full clean build though.

**Comment by vilvo** [comment]
I ran a full clean build http://ec2-52-59-242-235.eu-central-1.compute.amazonaws.com:8080/job/aero-build-release/13/

**Comment by mindThomas** [comment]
Was this a full build without space optimization flag?
Which AWS service do you have? And how much space did this clean build require?

I can't seem to find the full build log to conclude whether or not you also get the fetching errors.

**Comment by mindThomas** [comment]
Why did you close this?
Please notice that this error is still present, that is the following three packages still complains about fetch errors:
- zlib-native-1.2.8-r0
- libpcre-native-8.38-r0
- libpng-native-1.6.21-r0
