### ISSUE TITLE
meta-intel-realsense revision is incorrect

### ISSUE THREAD

**Issue by mindThomas** [intel-aero/intel-aero-manifest#7]
In the manifest file at the "meta-intel-realsense" line it currently says:
`<project name="meta-intel-realsense" remote="intel-realsense" path="poky/meta-intel-realsense" revision="82e9dbfd8783292f42f4a6fcc7bd5b8a6b1c567"/>`

The revision number here is incorrect and is missing an 'a' in the end. Instead it should be saying:
`<project name="meta-intel-realsense" remote="intel-realsense" path="poky/meta-intel-realsense" revision="82e9dbfd8783292f42f4a6fcc7bd5b8a6b1c567a"/>`

Refferring to: https://github.com/IntelRealSense/meta-intel-realsense/commit/82e9dbfd8783292f42f4a6fcc7bd5b8a6b1c567a

**Comment by lucasdemarchi** [comment]
Fixed already

**Comment by mindThomas** [comment]
Working late? ;-)
